-- =====================================================================
-- AutoVault sample catalogue data
-- ---------------------------------------------------------------------
-- Import AFTER database/schema.sql into an empty AutoVault database.
-- This file contains fictional catalogue inventory only. It creates no
-- users, administrators, favourites, requests, or personal information.
-- Vehicle identifications are the closest visual matches to the student-
-- supplied PDF photographs and should be reviewed before real-world use.
-- =====================================================================

USE autovault;

START TRANSACTION;

INSERT INTO vehicles
    (id, make, model, year, price, mileage, fuel_type, transmission,
     body_type, color, doors, seats, vin, description, status, is_featured)
VALUES
    (1, 'Honda', 'Civic Sedan', 2019, 22995.00, 68400, 'Petrol', 'Automatic',
     'Sedan', 'White', 4, 5, NULL,
     'A practical compact sedan with an efficient drivetrain, comfortable cabin, and everyday usability.',
     'available', 1),
    (2, 'Lincoln', 'Navigator', 2018, 48995.00, 74200, 'Petrol', 'Automatic',
     'SUV', 'Black', 4, 7, NULL,
     'A spacious luxury SUV with three-row seating, a refined cabin, and strong road presence.',
     'available', 1),
    (3, 'Ford', 'Police Utility', 2017, 19995.00, 112500, 'Petrol', 'Automatic',
     'SUV', 'White', 4, 5, NULL,
     'A durable utility vehicle configured for dependable fleet-style performance and all-weather use.',
     'available', 0),
    (4, 'Ford', 'Focus Hatchback', 2016, 14995.00, 89500, 'Petrol', 'Automatic',
     'Hatchback', 'Silver', 4, 5, NULL,
     'A compact hatchback offering flexible cargo space, easy manoeuvrability, and efficient commuting.',
     'available', 0),
    (5, 'Chevrolet', 'Impala', 1967, 44995.00, 98500, 'Petrol', 'Automatic',
     'Classic Sedan', 'Blue', 4, 5, NULL,
     'A preserved classic sedan with period styling, a spacious interior, and distinctive chrome details.',
     'available', 1),
    (6, 'Chevrolet', 'Impala', 1964, 52995.00, 86400, 'Petrol', 'Automatic',
     'Classic Sedan', 'White', 4, 5, NULL,
     'A vintage full-size sedan presented in a light finish with traditional American touring character.',
     'available', 0),
    (7, 'Dodge', 'Challenger', 1970, 74995.00, 72100, 'Petrol', 'Manual',
     'Sports Coupe', 'Black', 2, 4, NULL,
     'A classic muscle coupe combining dramatic styling, rear-wheel-drive character, and collector appeal.',
     'available', 1),
    (8, 'Cadillac', 'Eldorado Convertible', 1962, 68995.00, 80300, 'Petrol', 'Automatic',
     'Convertible', 'Cream', 2, 5, NULL,
     'A large classic convertible with elegant proportions, open-air touring, and period luxury details.',
     'available', 0),
    (9, 'Jaguar', 'E-Type', 1968, 119995.00, 57600, 'Petrol', 'Manual',
     'Sports Coupe', 'Silver', 2, 2, NULL,
     'A celebrated classic sports coupe with flowing bodywork, compact proportions, and driver-focused character.',
     'available', 1),
    (10, 'Dodge', 'Challenger R/T', 1970, 79995.00, 69400, 'Petrol', 'Manual',
     'Sports Coupe', 'Blue', 2, 4, NULL,
     'A vivid classic performance coupe with muscular styling and a purposeful grand-touring cabin.',
     'available', 1),
    (11, 'Chevrolet', 'Impala Convertible', 1959, 89995.00, 74300, 'Petrol', 'Automatic',
     'Convertible', 'White', 2, 5, NULL,
     'A landmark late-1950s convertible with sweeping lines, bright trim, and relaxed open-air cruising.',
     'available', 1),
    (12, 'Toyota', 'Yaris Sedan', 2017, 15995.00, 78200, 'Petrol', 'Automatic',
     'Sedan', 'Beige', 4, 5, NULL,
     'An economical compact sedan suited to city driving, daily commuting, and straightforward ownership.',
     'available', 0),
    (13, 'Toyota', 'Land Cruiser', 2020, 71995.00, 61500, 'Petrol', 'Automatic',
     'SUV', 'Black', 4, 7, NULL,
     'A full-size SUV designed for long-distance comfort, generous passenger space, and demanding terrain.',
     'available', 1),
    (14, 'Volvo', 'XC60', 2019, 38995.00, 65800, 'Hybrid', 'Automatic',
     'SUV', 'White', 4, 5, NULL,
     'A refined midsize SUV with Scandinavian-inspired design, flexible cargo room, and hybrid efficiency.',
     'available', 0),
    (15, 'Toyota', 'Land Cruiser', 2021, 77995.00, 52400, 'Petrol', 'Automatic',
     'SUV', 'Grey', 4, 7, NULL,
     'A capable premium SUV combining strong off-road ability with three-row practicality and road comfort.',
     'available', 1),
    (16, 'Land Rover', 'Range Rover Evoque', 2018, 35995.00, 70800, 'Petrol', 'Automatic',
     'SUV', 'White', 4, 5, NULL,
     'A compact luxury SUV with distinctive styling, an elevated driving position, and composed handling.',
     'available', 0),
    (17, 'Mercedes-Benz', 'G-Class', 2020, 139995.00, 43800, 'Petrol', 'Automatic',
     'SUV', 'Black', 4, 5, NULL,
     'An iconic luxury off-road SUV with upright design, premium appointments, and substantial capability.',
     'available', 1),
    (18, 'Hyundai', 'Tucson', 2019, 26995.00, 67300, 'Petrol', 'Automatic',
     'SUV', 'White', 4, 5, NULL,
     'A versatile compact SUV with a comfortable cabin, useful cargo space, and approachable road manners.',
     'available', 0),
    (19, 'Mitsubishi', 'Pajero Sport', 2020, 42995.00, 59400, 'Diesel', 'Automatic',
     'SUV', 'Black', 4, 7, NULL,
     'A rugged seven-seat SUV with diesel torque, off-road capability, and practical family accommodation.',
     'available', 0),
    (20, 'Suzuki', 'Jimny', 2021, 31995.00, 36700, 'Petrol', 'Automatic',
     'SUV', 'Yellow', 2, 4, NULL,
     'A compact off-road SUV with distinctive styling, short-wheelbase agility, and trail-ready proportions.',
     'available', 1);

INSERT INTO vehicle_images
    (vehicle_id, image_path, alt_text, is_primary, sort_order)
VALUES
    (1, 'assets/images/vehicles/vehicle-01-white-compact-sedan.jpg',
     'White compact sedan parked on a snowy street', 1, 1),
    (2, 'assets/images/vehicles/vehicle-02-black-luxury-suv.jpg',
     'Black luxury SUV outside a residential garage', 1, 1),
    (3, 'assets/images/vehicles/vehicle-03-white-police-utility.jpg',
     'White police utility vehicle beside a wooded road', 1, 1),
    (4, 'assets/images/vehicles/vehicle-04-silver-hatchback.jpg',
     'Silver hatchback viewed from the side', 1, 1),
    (5, 'assets/images/vehicles/vehicle-05-blue-classic-sedan.jpg',
     'Blue classic sedan displayed indoors', 1, 1),
    (6, 'assets/images/vehicles/vehicle-06-white-classic-sedan.jpg',
     'Front quarter view of a white classic sedan', 1, 1),
    (7, 'assets/images/vehicles/vehicle-07-black-classic-muscle-car.jpg',
     'Black classic muscle car in an exhibition hall', 1, 1),
    (8, 'assets/images/vehicles/vehicle-08-cream-classic-convertible.jpg',
     'Cream classic convertible displayed outdoors', 1, 1),
    (9, 'assets/images/vehicles/vehicle-09-silver-classic-sports-coupe.jpg',
     'Front view of a silver classic sports coupe', 1, 1),
    (10, 'assets/images/vehicles/vehicle-10-blue-classic-muscle-car.jpg',
     'Blue classic muscle car at an indoor show', 1, 1),
    (11, 'assets/images/vehicles/vehicle-11-white-classic-convertible.jpg',
     'White classic convertible at an outdoor event', 1, 1),
    (12, 'assets/images/vehicles/vehicle-12-beige-compact-sedan.jpg',
     'Beige compact sedan on a country road', 1, 1),
    (13, 'assets/images/vehicles/vehicle-13-black-full-size-suv.jpg',
     'Black full-size SUVs parked in a row', 1, 1),
    (14, 'assets/images/vehicles/vehicle-14-white-luxury-suv.jpg',
     'White luxury SUV driving on a city street', 1, 1),
    (15, 'assets/images/vehicles/vehicle-15-grey-full-size-suv.jpg',
     'Grey full-size SUV driving through a city', 1, 1),
    (16, 'assets/images/vehicles/vehicle-16-white-compact-luxury-suv.jpg',
     'White compact luxury SUV on display', 1, 1),
    (17, 'assets/images/vehicles/vehicle-17-black-luxury-off-road-suv.jpg',
     'Black luxury off-road SUV parked on a street', 1, 1),
    (18, 'assets/images/vehicles/vehicle-18-white-compact-suv.jpg',
     'White compact SUV parked near trees', 1, 1),
    (19, 'assets/images/vehicles/vehicle-19-black-off-road-suv.jpg',
     'Black off-road SUV in a misty field', 1, 1),
    (20, 'assets/images/vehicles/vehicle-20-yellow-compact-off-road-suv.jpg',
     'Yellow compact off-road SUV parked on a street', 1, 1);

-- Two selectable, meaningful options for every sample vehicle.
INSERT INTO vehicle_options
    (vehicle_id, option_group, option_name, price_adjustment, is_default, sort_order)
VALUES
    (1, 'Protection', 'All-weather floor mats', 195.00, 1, 1),
    (1, 'Technology', 'Driver-assistance package', 1295.00, 0, 2),
    (2, 'Comfort', 'Second-row captain chairs', 895.00, 1, 1),
    (2, 'Towing', 'Heavy-duty towing package', 1495.00, 0, 2),
    (3, 'Utility', 'Cargo management package', 495.00, 1, 1),
    (3, 'Protection', 'All-weather interior package', 295.00, 0, 2),
    (4, 'Technology', 'Navigation and camera package', 795.00, 1, 1),
    (4, 'Protection', 'Winter floor and cargo liners', 245.00, 0, 2),
    (5, 'Presentation', 'Show-detail preparation', 450.00, 1, 1),
    (5, 'Storage', 'Indoor fitted vehicle cover', 325.00, 0, 2),
    (6, 'Presentation', 'Show-detail preparation', 450.00, 1, 1),
    (6, 'Storage', 'Indoor fitted vehicle cover', 325.00, 0, 2),
    (7, 'Presentation', 'Show-detail preparation', 550.00, 1, 1),
    (7, 'Documentation', 'Collector documentation portfolio', 275.00, 0, 2),
    (8, 'Presentation', 'Show-detail preparation', 550.00, 1, 1),
    (8, 'Storage', 'Indoor fitted vehicle cover', 375.00, 0, 2),
    (9, 'Presentation', 'Show-detail preparation', 650.00, 1, 1),
    (9, 'Documentation', 'Collector documentation portfolio', 275.00, 0, 2),
    (10, 'Presentation', 'Show-detail preparation', 550.00, 1, 1),
    (10, 'Storage', 'Indoor fitted vehicle cover', 375.00, 0, 2),
    (11, 'Presentation', 'Show-detail preparation', 650.00, 1, 1),
    (11, 'Storage', 'Indoor fitted vehicle cover', 375.00, 0, 2),
    (12, 'Protection', 'All-weather floor mats', 195.00, 1, 1),
    (12, 'Technology', 'Rear camera package', 595.00, 0, 2),
    (13, 'Towing', 'Heavy-duty towing package', 1495.00, 1, 1),
    (13, 'Protection', 'All-weather cargo package', 395.00, 0, 2),
    (14, 'Technology', 'Advanced driver-assistance package', 1595.00, 1, 1),
    (14, 'Comfort', 'Heated rear-seat package', 695.00, 0, 2),
    (15, 'Towing', 'Heavy-duty towing package', 1495.00, 1, 1),
    (15, 'Protection', 'All-weather cargo package', 395.00, 0, 2),
    (16, 'Technology', 'Surround-view camera package', 1295.00, 1, 1),
    (16, 'Comfort', 'Cold-weather package', 895.00, 0, 2),
    (17, 'Comfort', 'Luxury rear-seat package', 2495.00, 1, 1),
    (17, 'Protection', 'All-weather interior package', 395.00, 0, 2),
    (18, 'Technology', 'Driver-assistance package', 1195.00, 1, 1),
    (18, 'Protection', 'All-weather floor and cargo liners', 295.00, 0, 2),
    (19, 'Off-road', 'Trail protection package', 995.00, 1, 1),
    (19, 'Towing', 'Tow-bar package', 895.00, 0, 2),
    (20, 'Off-road', 'Trail protection package', 795.00, 1, 1),
    (20, 'Storage', 'Roof cargo carrier', 595.00, 0, 2);

COMMIT;
